### ISSUE TITLE
oss-fuzz 31726 graphicsmagick:coder_JP2_fuzzer: ASSERT: absstepsize >= 0

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#277]
oss-fuzz 31726 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31726.tar.gz](https://github.com/jasper-software/jasper/files/6135051/oss-fuzz-31726.tar.gz)

**Comment by mdadams** [comment]
I cannot reproduce a failure for the image file provided.  I obtain the following, for example:
imginfo --debug-level 0 < provided_jp2_file.jp2
warning: not enough tile data (3 bytes)
RCT requires all components have the same domain
error: cannot decode code stream
cannot load image
I do not obtain any sanitizer complaints.
I am going to close this issue assuming that it has been fixed by other recent changes.  If you still have this problem, please provide more information so that it is possible for me to reproduce the problem.

**Comment by bobfriesenhahn** [comment]
On Sun, 14 Mar 2021, Michael Adams wrote:
> I do not obtain any sanitizer complaints.

I expect that this is because the utility you are using does not work 
the same.

> I am going to close this issue assuming that it has been fixed by other recent changes.  If you still have this problem, please provide more information so that it is possible for me to reproduce the problem.

The GraphicsMagick oss-fuzz build history may be seen at 
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#graphicsmagick

The most recent build was done on 3/14/2021 at 9:55 AM CST.  The 
JasPer sources are cloned from scratch for each build.

Oss-fuzz is showing that the test case still crashes.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
When I follow the link that you gave, I don't see any fuzz error reports.  I just see badges for builds with the most recent one showing as successful.  Furthermore, when I click on the badge I just get an extremely long log file, which is not one of the errors reports that you have sent to me. Please keep in mind that I have never used oss-fuzz. So things that may be obvious to you may not be obvious to me.

**Comment by bobfriesenhahn** [comment]
On Sun, 14 Mar 2021, Michael Adams wrote:
> I do not obtain any sanitizer complaints.
> I am going to close this issue assuming that it has been fixed by other recent changes.  If you still have this problem, please provide more information so that it is possible for me to reproduce the problem.

Regardless of oss-fuzz not closing this issue, I am not able to 
reproduce the assertion any more in my own builds.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
In that case, I'm going to assume that this was a false positive from oss-fuzz (or maybe the problem got fixed in some of my recent code changes?).  Since neither one of us can reproduce the problem now, I don't know what else can be done.

**Comment by bobfriesenhahn** [comment]
On Sun, 14 Mar 2021, Michael Adams wrote:

> When I follow the link that you gave, I don't see any fuzz error 
> reports.  I just see badges for builds with the most recent one 
> showing as successful.  Furthermore, when I click on the badge I 
> just get an extremely long log file, which is not one of the errors 
> reports that you have sent to me. Please keep in mind that I have 
> never used oss-fuzz. So things that may be obvious to you may not be 
> obvious to me.

Yes, that is just the oss-fuzz project build information page.

I certainly understand that you do not have experience with oss-fuzz. 
In perhaps 30 days time, bugs which were fixed will become public, and 
in perhaps 90 days time, bugs which were not fixed will become public 
on the page at 
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=graphicsmagick&can=1

I do not have any administrative authority for oss-fuzz at all.  I am 
able to write comments on the bug reports it opens and that is it. 
The only way I can cause a report be marked as "Verified" is by fixing 
the source code so the problem does not happen.  I am unable to share 
issues with someone else except for by manually copying the report 
from the web page (as I did for you).

Oss-fuzz provides quite powerful fuzzing capabilities (perhaps using 
thousands of machines) but it is also totally automated.  The basic
contraints for test cases (time and memory) are determined by oss-fuzz 
and a project has no control over them.

I would encourage JasPer to indepently join oss-fuzz, but be aware 
that it is extremely good at finding any flaw and that the only 
recourse is to fix it somehow in source code.  Now that GraphicsMagick 
has added JasPer to its oss-fuzz build, any detected JasPer flaw is 
blamed on GraphicsMagick.

The decision to join oss-fuzz is a "Damned if you do and damned if you 
don't" situation given that there are major benefits to joining 
(including improving public trust) but it may involve a major 
drubbing (which I like to call "waterboarding").  Any "dirty laundry" 
will become evident to all in 90 days.

You may see that I have been on this treadmill for four years already, 
while I had already been on the Coverity treadmill, and on the 
receiving end of reports from other people who run fuzzers.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by bobfriesenhahn** [comment]
On Sun, 14 Mar 2021, Michael Adams wrote:

> In that case, I'm going to assume that this was a false positive 
> from oss-fuzz (or maybe the problem got fixed in some of my recent 
> code changes?).  Since neither one of us can reproduce the problem 
> now, I don't know what else can be done.

It would be good to wait a day.

Something to be aware of is that oss-fuzz is using very recent 
compilers which may still be in development phases.  It is unlikely 
that either of us would have been exposed to such new compilers. 
From the JasPer build, I see that it says it is being built using 
Clang 12.0.0.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by bobfriesenhahn** [comment]
I just noticed something interesting about this issue.  The oss-fuzz 
report says it is for "Job Type: libfuzzer_asan_i386_graphicsmagick".

What this means is that this is a build for 32-bit i386 code rather 
than the 64-bits most of us are using today.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
Partly due to my involvement in ISO C++ standardization and partly due to the fact that I like to teach the most recent version of the C++ standard to my students, I build both GCC and Clang directly from their official Git repositories on a somewhat regular basis.  As luck would have it, I am in the process of building several versions of GCC and Clang today (including the most recent development versions).  I can try things with the latest development versions of GCC and Clang later today (assuming that the builds are successful).

**Comment by mdadams** [comment]
Well 32 bit changes everything.  There could certainly be bugs that manifest themselves in 32 bit that are fine in 64 bit.  The only problem is that I don't have any 32 bit machines for testing.  I don't even think that TravisCI has a 32 bit configuration available.  JasPer automatically tests every commit to master for the cases of arm64, x86-64, and powerpc (using TravisCI) with both GCC and Clang.

**Comment by mdadams** [comment]
@bobfriesenhahn Thanks for the clarification about how oss-fuzz works.  I now understand why I didn't see any error reports.

**Comment by mdadams** [comment]
@bobfriesenhahn Incidentally, I just tried a development version of Clang 13 that I already had built from a few days ago and there is no failure detected in JasPer for your test case.  So, if this issue is real (i.e., not a false positive), I am guessing that it only affects 32 bit.

**Comment by bobfriesenhahn** [comment]
On Sun, 14 Mar 2021, Michael Adams wrote:

> @bobfriesenhahn Incidentally, I just tried a development version of Clang 13 that I already had built from a few days ago and there is no failure detected in JasPer for your test case.  So, if this issue is real (i.e., not a false positive), I am guessing that it only affects 32 bit.

I suspect that if we just wait a day that oss-fuzz will decide that 
the issue is fixed.  The problem is that workers keep on working 
although a newer build has been produced.

From looking at the indicated sources, it seems like they were not 
updated recently so it may be day-old code.

While I can easily use Autoconf's configure script to build 32-bit 
apps on my 64-bit Linux system, it appears that this is very hard to 
accomplish using cmake.  I tried using a toolchain file but it almost 
seems like the project needs to be designed to use a toolchain file.

The best information that Google finds for me is that "maybe we should 
write some documentation about how to do that.

From an end-user perspective, I really am hating cmake at the moment.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt
